'use strict';
// C++ の文法リスト（競プロでよく使うものだけ）。ステップ図はなく、sheet を一覧で出す。
// sheet: [{ title, rows: [[コード, 説明], ...] }]

registerTopic('cpp', {
  title: '覚えておきたい C++ の文法',
  explain: [
    'この本のコードを読み書きするのに必要な C++ の文法を、よく使う順にまとめた。最初に全部覚える必要はなく、分からない書き方が出てきたら戻ってくればよい。',
    'コードはどれも #include <bits/stdc++.h> と using namespace std; を書いた前提で動く。',
  ],
  sheet: [
    { title: '基本の形', rows: [
      ['#include <bits/stdc++.h>', '標準ライブラリをまとめて読み込む（GCC の機能。AtCoder で使える）。'],
      ['using namespace std;', 'std::cout を cout と書けるようにする。'],
      ['int main() {\n  // ここに書く\n}', 'プログラムはここから始まる。'],
    ] },
    { title: '型', rows: [
      ['int x = 5;', '整数。だいたい ±2 × 10^9 まで。'],
      ['long long x = 1e18;', '大きい整数。だいたい ±9 × 10^18 まで。答えが 10^9 を超えそうならこれ。'],
      ['long long y = 1LL * a * b;', 'int どうしの掛け算はあふれる。片方を long long にしてから掛ける。'],
      ['double d = 3.14;', '小数。'],
      ['char c = \'a\';', '1 文字。シングルクォートで囲む。'],
      ['string s = "abc";', '文字列。ダブルクォートで囲む。'],
      ['bool ok = true;', '真偽値（true / false）。'],
      ['auto v = a.size();', '型を右辺から決めてもらう。'],
      ['const int MOD = 998244353;', '変わらない値には const を付ける。'],
    ] },
    { title: '入出力', rows: [
      ['int n; cin >> n;', '標準入力から読む。空白・改行は読み飛ばされる。'],
      ['cin >> a >> b;', '続けて読む。'],
      ['for (auto &x : a) cin >> x;', '配列をまとめて読む（a は先に大きさを決めておく）。'],
      ['cout << x << \'\\n\';', '出力して改行。'],
      ['cout << a << \' \' << b << endl;', '空白区切りで出力。endl は改行して出力を流す（たくさん出すときは \'\\n\' が速い）。'],
      ['cout << (ok ? "Yes" : "No") << endl;', 'Yes / No を出す決まった形。'],
      ['cout << fixed << setprecision(10) << d;', '小数を小数点以下 10 桁で出す。'],
      ['ios::sync_with_stdio(false);\ncin.tie(nullptr);', 'main の最初に書くと入出力が速くなる。'],
      ['getline(cin, s);', '空白を含む 1 行をまるごと読む。'],
    ] },
    { title: '条件分岐とループ', rows: [
      ['if (x > 0) { ... }\nelse if (x == 0) { ... }\nelse { ... }', '条件分岐。等しいかは ==（= は代入）。'],
      ['a && b, a || b, !a', 'かつ・または・でない。'],
      ['int m = (a > b ? a : b);', '三項演算子。条件 ? 真のとき : 偽のとき。'],
      ['for (int i = 0; i < n; i++) { ... }', 'i = 0, 1, …, n-1 で回す。一番よく使う形。'],
      ['for (int i = n - 1; i >= 0; i--) { ... }', '逆向きに回す。'],
      ['for (auto x : a) { ... }', '配列の中身を先頭から順に取り出す。'],
      ['for (auto &x : a) x *= 2;', '& を付けると中身を書き換えられる。'],
      ['while (n > 0) { ... }', '条件が成り立つ間くり返す。'],
      ['break; / continue;', 'ループを抜ける／次の回へ飛ぶ。'],
    ] },
    { title: '配列（vector）', rows: [
      ['vector<int> a(n);', '長さ n の配列（中身は 0）。'],
      ['vector<long long> a(n, -1);', '長さ n、全部 -1 で埋める。'],
      ['vector<vector<int>> g(h, vector<int>(w));', 'h 行 w 列の二次元配列。g[i][j] で使う。'],
      ['a[i]', 'i 番目（0 始まり）。範囲外を触ると RE や WA になる。'],
      ['a.size()', '要素の数。'],
      ['a.push_back(x);', '末尾に足す。'],
      ['a.pop_back();', '末尾を消す。'],
      ['a.back()', '末尾の要素。'],
      ['a.empty()', '空なら true。'],
      ['a.begin(), a.end()', '先頭と「末尾の次」。sort などの関数に範囲として渡す。'],
    ] },
    { title: '文字列（string）', rows: [
      ['s.size()', '文字数。'],
      ['s[i]', 'i 文字目（char）。'],
      ['s += \'x\';  s += "yz";', '末尾に文字・文字列をつなぐ。'],
      ['s.substr(i, len)', 'i 文字目から len 文字を取り出す。'],
      ['s[i] - \'0\'', '数字の文字を整数にする（\'7\' → 7）。'],
      ['c - \'a\'', '小文字を 0〜25 の番号にする。'],
      ['to_string(x)', '整数を文字列にする。'],
      ['stoi(s), stoll(s)', '文字列を int / long long にする。'],
      ['s == t, s < t', '文字列は == や < で比べられる（辞書順）。'],
    ] },
    { title: 'よく使う関数', rows: [
      ['max(a, b), min(a, b)', '大きい方・小さい方。型をそろえる（max(x, 0LL) など）。'],
      ['max({a, b, c})', '3 つ以上なら { } で囲む。'],
      ['swap(a, b);', '入れ替える。'],
      ['abs(x)', '絶対値。'],
      ['sort(a.begin(), a.end());', '小さい順に並べる。'],
      ['sort(a.rbegin(), a.rend());', '大きい順に並べる。'],
      ['reverse(a.begin(), a.end());', '逆順にする。文字列にも使える。'],
      ['accumulate(a.begin(), a.end(), 0LL)', '合計。最初の値を 0LL にすると long long で足す。'],
      ['*max_element(a.begin(), a.end())', '最大値（* を付けて値を取り出す）。'],
      ['count(a.begin(), a.end(), x)', 'x の個数。'],
      ['lower_bound(a.begin(), a.end(), x) - a.begin()', 'ソート済みの a で、x 以上が最初に出る位置（二分探索。3章）。'],
      ['a.erase(unique(a.begin(), a.end()), a.end());', 'ソート後に書くと、重複を消せる。'],
      ['do { ... } while (next_permutation(a.begin(), a.end()));', 'ソート済みの a から、すべての並べ方を順に試す。'],
      ['gcd(a, b), lcm(a, b)', '最大公約数・最小公倍数（C++17）。'],
    ] },
    { title: 'pair と構造化束縛', rows: [
      ['pair<int, int> p = {3, 5};', '2 つの値の組。'],
      ['p.first, p.second', '1 つ目・2 つ目。'],
      ['vector<pair<int, int>> v;', '組の配列。sort すると first で比べ、同じなら second で比べる。'],
      ['auto [x, y] = p;', '組をばらして受け取る（C++17）。'],
      ['for (auto [k, v] : mp) { ... }', 'map を回すときにも使える。'],
    ] },
    { title: 'データ構造（8章）', rows: [
      ['stack<int> st; st.push(x); st.top(); st.pop();', 'スタック。最後に入れたものから出す。'],
      ['queue<int> q; q.push(x); q.front(); q.pop();', 'キュー。最初に入れたものから出す（幅優先探索で使う）。'],
      ['priority_queue<int> pq; pq.push(x); pq.top(); pq.pop();', '優先度付きキュー。top は最大値。'],
      ['priority_queue<int, vector<int>, greater<int>> pq;', '最小値を取り出す版（ダイクストラ法で使う）。'],
      ['map<string, int> mp; mp[s]++;', '連想配列。キーで引ける。ない キーを [ ] で触ると 0 で作られる。'],
      ['mp.count(k)', 'キー k があれば 1、なければ 0。'],
      ['set<int> st; st.insert(x); st.erase(x);', '集合。重複なし、小さい順に並ぶ。'],
      ['st.count(x)', 'x が入っていれば 1。'],
      ['*st.begin(), *st.rbegin()', '最小値・最大値。'],
      ['st.lower_bound(x)', 'x 以上で最小の要素の位置（set では a.begin() 版ではなくこちらを使う）。'],
      ['multiset<int> ms; ms.erase(ms.find(x));', '重複ありの集合。1 個だけ消すときは find を使う。'],
      ['deque<int> dq; dq.push_front(x); dq.push_back(x);', '両端に足し引きできる配列。'],
    ] },
    { title: '関数とラムダ式', rows: [
      ['int add(int a, int b) {\n  return a + b;\n}', '関数。main より上に書く。'],
      ['void f(vector<int> &a) { ... }', '& を付けると配列をコピーせずに渡す（中身を書き換えられる）。大きい配列はこう渡す。'],
      ['long long fact(int n) {\n  if (n == 0) return 1;\n  return n * fact(n - 1);\n}', '再帰関数（7章のコラム）。'],
      ['auto f = [&](int x) { return x * 2; };', 'ラムダ式。main の中で書けて、[&] で周りの変数を使える。'],
      ['sort(a.begin(), a.end(), [](int x, int y) { return x > y; });', '並べ方をラムダで決める。true なら x を先に置く。'],
    ] },
    { title: 'ビット演算（1章）', rows: [
      ['1 << n', '2^n。n ビットの全パターンは 0 〜 (1 << n) - 1。'],
      ['(s >> i) & 1', 's の i ビット目が 1 か（ビット全探索）。'],
      ['s | (1 << i)', 'i ビット目を 1 にする。'],
      ['a & b, a | b, a ^ b', 'AND・OR・XOR。'],
      ['__builtin_popcount(s)', '1 のビットの数（long long なら __builtin_popcountll）。'],
      ['1LL << 40', '31 ビット以上ずらすときは 1LL にする。'],
    ] },
    { title: '割り算と余り', rows: [
      ['7 / 2', '整数どうしの割り算は切り捨て（3）。'],
      ['(a + b - 1) / b', '正の整数の割り算を切り上げる。'],
      ['7 % 3', '余り（1）。'],
      ['(x % m + m) % m', 'x が負でも 0 〜 m-1 の余りにする（C++ の % は負になりうる）。'],
      ['(a * b) % MOD', '掛けるたびに余りを取る（5章）。a, b は long long にしておく。'],
      ['(double)a / b', '小数で割りたいときは片方を double にする。'],
    ] },
    { title: 'よく使う定数・書き方', rows: [
      ['const long long INF = 1e18;', '「まだ届いていない」を表す大きい値（DP やダイクストラ法の初期値）。'],
      ['const int dx[4] = {1, 0, -1, 0};\nconst int dy[4] = {0, 1, 0, -1};', 'グリッドの上下左右に動くときの差分。'],
      ['if (0 <= nx && nx < h && 0 <= ny && ny < w)', 'グリッドの範囲内かを確かめる。'],
      ['#define rep(i, n) for (int i = 0; i < (n); i++)', 'よく見るマクロ。rep(i, n) で for を短く書ける。'],
    ] },
  ],
});
